In [5]:
import pandas as pd
import pickle

In [6]:
model = pickle.load(open("../code/model_file/best_model.pkl","rb"))
scaler = pickle.load(open("../code/model_file/scaling.pkl","rb"))

In [7]:
model.predict_proba([[0,79.33,1,78.33,0,1,77.48,1,1,86.5,0,66.28,200000.0]])

array([[0.55696203, 0.44303797]])

In [8]:
model.predict([[0,73.0,1,79.0,1,0,72.0,0,0,91.34,0,61.29,231000.0]])

array([0], dtype=int64)

In [9]:
df = pd.read_csv("../code/clean_data/clean_train.csv", )

In [10]:
df.head()

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  workex  \
0       0  67.00      0  91.00      0      0     58.00         1       0   
1       0  79.33      1  78.33      0      1     77.48         1       1   
2       0  65.00      1  68.00      1      2     64.00         0       0   
3       0  56.00      1  52.00      1      1     52.00         1       0   
4       0  85.80      1  73.60      1      0     73.30         0       0   

   etest_p  specialisation  mba_p  status         salary  
0     55.0               1  58.80       1  270000.000000  
1     86.5               0  66.28       1  200000.000000  
2     75.0               0  57.80       1  250000.000000  
3     66.0               1  59.43       0  288655.405405  
4     96.8               0  55.50       1  425000.000000

In [11]:
X = df.drop(columns=['status'])

In [12]:
X

gender  ssc_p  ssc_b  hsc_p  hsc_b  hsc_s  degree_p  degree_t  workex  \
0         0  67.00      0  91.00      0      0     58.00         1       0   
1         0  79.33      1  78.33      0      1     77.48         1       1   
2         0  65.00      1  68.00      1      2     64.00         0       0   
3         0  56.00      1  52.00      1      1     52.00         1       0   
4         0  85.80      1  73.60      1      0     73.30         0       0   
..      ...    ...    ...    ...    ...    ...       ...       ...     ...   
210       0  80.60      0  82.00      0      0     77.60         0       0   
211       0  58.00      0  60.00      0      1     72.00         1       0   
212       0  67.00      0  67.00      0      0     73.00         0       1   
213       1  74.00      0  66.00      0      0     58.00         0       0   
214       0  62.00      1  58.00      0      1     53.00         0       0   

     etest_p  specialisation  mba_p         salary  
0       55.0               1  58.80  270000.000000  
1       86.5               0  66.28  200000.000000  
2       75.0               0  57.80  250000.000000  
3       66.0               1  59.43  288655.405405  
4       96.8               0  55.50  425000.000000  
..       ...             ...    ...            ...  
210     91.0               0  74.49  400000.000000  
211     74.0               0  53.62  275000.000000  
212     59.0               0  69.72  295000.000000  
213     70.0               1  60.23  204000.000000  
214     89.0               1  60.22  288655.405405  

[215 rows x 13 columns]

In [13]:
y = df['status']

In [14]:
scaled_X = scaler.transform(X)

In [15]:
df_new = pd.DataFrame(scaled_X, columns=X.columns)

In [16]:
model.predict([scaled_X[0]])

array([1], dtype=int64)

In [17]:
model.score(scaled_X, y)

0.4511627906976744

In [18]:
from sklearn.metrics import precision_score, recall_score

In [19]:
X.columns

Index(['gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p',
       'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p', 'salary'],
      dtype='object')

In [20]:
df_new

gender     ssc_p     ssc_b     hsc_p     hsc_b     hsc_s  degree_p  \
0   -0.728431 -0.036777 -0.973680  2.418803 -0.805203 -0.913191 -1.110792   
1   -0.728431  1.069398  1.027032  1.219611 -0.805203  0.737154  1.449157   
2   -0.728431 -0.216205  1.027032  0.241895  1.241923  2.387500 -0.322307   
3   -0.728431 -1.023632  1.027032 -1.272475  1.241923  0.737154 -1.899277   
4   -0.728431  1.649848  1.027032  0.771925  1.241923 -0.913191  0.899846   
..        ...       ...       ...       ...       ...       ...       ...   
210 -0.728431  1.183335 -0.973680  1.566969 -0.805203 -0.913191  1.464927   
211 -0.728431 -0.844204 -0.973680 -0.515290 -0.805203  0.737154  0.729007   
212 -0.728431 -0.036777 -0.973680  0.147247 -0.805203 -0.913191  0.860422   
213  1.372813  0.591222 -0.973680  0.052599 -0.805203 -0.913191 -1.110792   
214 -0.728431 -0.485347  1.027032 -0.704586 -0.805203  0.737154 -1.767863   

     degree_t    workex   etest_p  specialisation     mba_p    salary  
0    1.005858 -0.717741 -1.284444        1.083473 -0.592736 -0.254907  
1    1.005858  1.393261  1.180504       -0.922958  0.689164 -1.096897  
2   -0.689409 -0.717741  0.280602       -0.922958 -0.764113 -0.495476  
3    1.005858 -0.717741 -0.423668        1.083473 -0.484769 -0.030512  
4   -0.689409 -0.717741  1.986502       -0.922958 -1.158281  1.609500  
..        ...       ...       ...             ...       ...       ...  
210 -0.689409 -0.717741  1.532639       -0.922958  2.096171  1.308789  
211  1.005858 -0.717741  0.202350       -0.922958 -1.480470 -0.194765  
212 -0.689409  1.393261 -0.971434       -0.922958  1.278702  0.045804  
213 -0.689409 -0.717741 -0.110659        1.083473 -0.347667 -1.048783  
214 -0.689409 -0.717741  1.376135        1.083473 -0.349381 -0.030512  

[215 rows x 13 columns]

In [21]:
y

0      1
1      1
2      1
3      0
4      1
      ..
210    1
211    1
212    1
213    1
214    0
Name: status, Length: 215, dtype: int64

In [22]:
df_new['status'] = y

In [23]:
df_new

gender     ssc_p     ssc_b     hsc_p     hsc_b     hsc_s  degree_p  \
0   -0.728431 -0.036777 -0.973680  2.418803 -0.805203 -0.913191 -1.110792   
1   -0.728431  1.069398  1.027032  1.219611 -0.805203  0.737154  1.449157   
2   -0.728431 -0.216205  1.027032  0.241895  1.241923  2.387500 -0.322307   
3   -0.728431 -1.023632  1.027032 -1.272475  1.241923  0.737154 -1.899277   
4   -0.728431  1.649848  1.027032  0.771925  1.241923 -0.913191  0.899846   
..        ...       ...       ...       ...       ...       ...       ...   
210 -0.728431  1.183335 -0.973680  1.566969 -0.805203 -0.913191  1.464927   
211 -0.728431 -0.844204 -0.973680 -0.515290 -0.805203  0.737154  0.729007   
212 -0.728431 -0.036777 -0.973680  0.147247 -0.805203 -0.913191  0.860422   
213  1.372813  0.591222 -0.973680  0.052599 -0.805203 -0.913191 -1.110792   
214 -0.728431 -0.485347  1.027032 -0.704586 -0.805203  0.737154 -1.767863   

     degree_t    workex   etest_p  specialisation     mba_p    salary  status  
0    1.005858 -0.717741 -1.284444        1.083473 -0.592736 -0.254907       1  
1    1.005858  1.393261  1.180504       -0.922958  0.689164 -1.096897       1  
2   -0.689409 -0.717741  0.280602       -0.922958 -0.764113 -0.495476       1  
3    1.005858 -0.717741 -0.423668        1.083473 -0.484769 -0.030512       0  
4   -0.689409 -0.717741  1.986502       -0.922958 -1.158281  1.609500       1  
..        ...       ...       ...             ...       ...       ...     ...  
210 -0.689409 -0.717741  1.532639       -0.922958  2.096171  1.308789       1  
211  1.005858 -0.717741  0.202350       -0.922958 -1.480470 -0.194765       1  
212 -0.689409  1.393261 -0.971434       -0.922958  1.278702  0.045804       1  
213 -0.689409 -0.717741 -0.110659        1.083473 -0.347667 -1.048783       1  
214 -0.689409 -0.717741  1.376135        1.083473 -0.349381 -0.030512       0  

[215 rows x 14 columns]

In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X = df_new.drop(columns=['status'], axis=1)
y = df_new['status']
X_train, X_test, y_train, y_test = train_test_split(X,y)

In [26]:
X_train.shape

(161, 13)

In [27]:
X_test.shape

(54, 13)

In [28]:
model.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=2, min_samples_leaf=50)

In [29]:
model.score(X_train,y_train)

0.7453416149068323

In [30]:
model.score(X_test,y_test)

0.7777777777777778

In [31]:
y_pred = model.predict(X_test)

In [32]:
df_new

gender     ssc_p     ssc_b     hsc_p     hsc_b     hsc_s  degree_p  \
0   -0.728431 -0.036777 -0.973680  2.418803 -0.805203 -0.913191 -1.110792   
1   -0.728431  1.069398  1.027032  1.219611 -0.805203  0.737154  1.449157   
2   -0.728431 -0.216205  1.027032  0.241895  1.241923  2.387500 -0.322307   
3   -0.728431 -1.023632  1.027032 -1.272475  1.241923  0.737154 -1.899277   
4   -0.728431  1.649848  1.027032  0.771925  1.241923 -0.913191  0.899846   
..        ...       ...       ...       ...       ...       ...       ...   
210 -0.728431  1.183335 -0.973680  1.566969 -0.805203 -0.913191  1.464927   
211 -0.728431 -0.844204 -0.973680 -0.515290 -0.805203  0.737154  0.729007   
212 -0.728431 -0.036777 -0.973680  0.147247 -0.805203 -0.913191  0.860422   
213  1.372813  0.591222 -0.973680  0.052599 -0.805203 -0.913191 -1.110792   
214 -0.728431 -0.485347  1.027032 -0.704586 -0.805203  0.737154 -1.767863   

     degree_t    workex   etest_p  specialisation     mba_p    salary  status  
0    1.005858 -0.717741 -1.284444        1.083473 -0.592736 -0.254907       1  
1    1.005858  1.393261  1.180504       -0.922958  0.689164 -1.096897       1  
2   -0.689409 -0.717741  0.280602       -0.922958 -0.764113 -0.495476       1  
3    1.005858 -0.717741 -0.423668        1.083473 -0.484769 -0.030512       0  
4   -0.689409 -0.717741  1.986502       -0.922958 -1.158281  1.609500       1  
..        ...       ...       ...             ...       ...       ...     ...  
210 -0.689409 -0.717741  1.532639       -0.922958  2.096171  1.308789       1  
211  1.005858 -0.717741  0.202350       -0.922958 -1.480470 -0.194765       1  
212 -0.689409  1.393261 -0.971434       -0.922958  1.278702  0.045804       1  
213 -0.689409 -0.717741 -0.110659        1.083473 -0.347667 -1.048783       1  
214 -0.689409 -0.717741  1.376135        1.083473 -0.349381 -0.030512       0  

[215 rows x 14 columns]

In [35]:
column_names = scaler.feature_names_in_
column_names

array(['gender', 'ssc_p', 'ssc_b', 'hsc_p', 'hsc_b', 'hsc_s', 'degree_p',
       'degree_t', 'workex', 'etest_p', 'specialisation', 'mba_p',
       'salary'], dtype=object)

In [43]:
import numpy as np
df['new'] = df_new.drop(columns=['status'], axis=1)
df_scaled = scaler.transform(df_new)

ValueError: Expected a 1D array, got an array with shape (215, 13)

In [42]:
np.array(df_new)[0]

array([-0.72843136, -0.03677679, -0.97367959,  2.41880277, -0.80520286,
       -0.91319133, -1.11079196,  1.00585843, -0.71774056, -1.2844437 ,
        1.08347268, -0.5927363 , -0.25490688,  1.        ])